service: supplier-portal-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  architecture: arm64
  stage: dev
  region: ap-southeast-2
  memorySize: 2048
  logRetentionInDays: 5
  timeout: 30

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
